version: "3.8"
services:

  nodered1:
    image: yoctu/nodered:latest
    command: npm start
    volumes:
      - type: volume
        source: NODERED1
        target: /data
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=prod
      - PORT=80
      
volumes:
  NODERED1:
